### ISSUE TITLE
오작동 문의

### ISSUE THREAD

**Issue by smbslt3** [monologg/GoEmotions-Korean#1]
안녕하세요

`'끊었던 담배 한 대 태우고 싶다. 이땅의 늙은 아버지들은 지금도 모르스 부호를 보내고 있다. 그것을 아는 자식들도 어찌할 방법이 없다.'`

위 문장을 goemotions 함수에 넣으면

`[{'labels': [], 'scores': []}]`

위와 같이 결과가 나오네요.

이상하게도, `끊었던 담배`를 `끊었던담배`로 바꾸면 이상 없이 결과가 나옵니다. 왜 이러는 걸까요?
위와 같이 에러가 나는 문장들은 아래와 같습니다.

- 끊었던 담배 한 대 태우고 싶다. 이땅의 늙은 아버지들은 지금도 모르스 부호를 보내고 있다. 그것을 아는 자식들도 어찌할 방법이 없다.
- 말이 필요없는 영화 모두 꼭 한번쯤은 봐야할법한 영화입니다. 그리고 조여정이 개인적으로 크게 한껀 한것같습니다
- 영화관에 초딩들 들여보내지마세요 ㅠㅠ 옆옆자리 초딩이 보던데..15세도 후한데 그것보다 어리면 안될거같아요
- 흠... 너무 기대한듯...
- 솔직히 이게 영화인가 싶고, 이런 영화가 상을 휩쓸었다는 것이 도대체 이 시대가 어디로 가고 있는가 싶어 허탈하다. 한 마디로 칙칙하고 별나고 불쾌하다. 같은 소재와 주제로도 더 밝고 희망적이고 상쾌한 영화를 만...
- 코로나 첫 사망자가 발생한 날, 청와대에서는 대통령과 감독이 짜파구리를 먹으며 성대한 오찬이 벌어지고 있었다. 기생충의 플롯이 현실에서 완성되는 순간.
- 19세 걸어야될듯... 민망한 장면이 한 둘이 아님 기대 안하고 보길 잘했다
- 상받은거 으스대느라 호사스런 궁궐에 들어가 짜파구리 쳐먹던 악마의 모습.... 인간이 만든 영화가 아님. 오스카트로피 다 빠게버려야. 사람이 죽어나고 역병이 걸리고 수천만이 벌벌 떨때 웃고 즐기던 그 모습. 그 모습...
- 노력하지 않고 남을 속이려는 사람들이 가난한 사람들로 그려져서 싫었다. 실제로는 부자들이 더 그런것 같은데 말이다. 가난해도 열심히 노력하며 행복하게 사는 사람들이 더 많다. 그런 사람들이 영화의 주인공이어야지. ...
- 억지로 감독들이 보기에 좋게 보이려고 노력한 영화. 억지로 강하게 묶어 놓아 한편의 시조를 보고온 느낌이 드는 영화. 그리고 감독이 주고자한 의미는 무엇일까? 분수를 지키고 살아라?
- 동정의 가치도 없는 범죄자 가족
- 빈부격차를 비판하는 내용인데 현 영화관 독점 상영에 관해 봉준호씨의 의견 듣기를 희망합니다.
- 알라딘볼걸또속았다!!
- 기대하고 갔는데 나올땐 뭔가 무겁고 찝찝함이 느껴지는 영화였다...
- 인생이 모아니면 도라고 착각하게 만드는 영화 기대하고 봤다 피봄
- 솔직한 평을 한다면 ? 초반 한시간동안 코미디요소도 그렇게 좋지만은 않았다. 현실을 반영한다고 했지만 결국 일가족 사기단으로 밖에 안 보였고, 기생당하는 숙주의 역활로 나오는 부자 부부가 그렇게 쉽게 사람을 쓴다는 ...
- 이걸 보고 머리에 기생충이 생길거 같다.영화를 보지 않았으면 이런 허무함은 느끼지 않아도 됐을지도,,추천은 하지 않는다
- 이거15세라뇨. 15세안본는거좋아요. 처음인데 끝나고. 기분이상합니다. 영화보고 기분좋아야되는대. 이상합니다. 평보고. 너무현실라고하는대. 저는라니라고봅니다

**Comment by monologg** [comment]
```python
goemotions = MultiLabelPipeline(
    model=model,
    tokenizer=tokenizer,
    threshold=0.3
)
```

여기서 `threshold`를 넘지 못한 값은 보여주지 않는 방식으로 설계되어 있습니다. 모든 28개의 emotion에 대해서 확률값을 보고 싶으면 `threshold=0.0`으로 정의해서 코드를 돌리면 될 것 같습니다.

**Comment by monologg** [comment]
```python
from multilabel_pipeline import MultiLabelPipeline
from transformers import ElectraTokenizer
from model import ElectraForMultiLabelClassification
from pprint import pprint


tokenizer = ElectraTokenizer.from_pretrained("monologg/koelectra-base-finetuned-goemotions")
model = ElectraForMultiLabelClassification.from_pretrained("monologg/koelectra-base-finetuned-goemotions")

goemotions = MultiLabelPipeline(
    model=model,
    tokenizer=tokenizer,
    threshold=0.3,
)

texts = [
    "끊었던 담배 한 대 태우고 싶다. 이땅의 늙은 아버지들은 지금도 모르스 부호를 보내고 있다. 그것을 아는 자식들도 어찌할 방법이 없다.",
    "끊었던담배 한 대 태우고 싶다. 이땅의 늙은 아버지들은 지금도 모르스 부호를 보내고 있다. 그것을 아는 자식들도 어찌할 방법이 없다.",
    "말이 필요없는 영화 모두 꼭 한번쯤은 봐야할법한 영화입니다. 그리고 조여정이 개인적으로 크게 한껀 한것같습니다"
]

pprint(goemotions(texts))
```

```python
from multilabel_pipeline import MultiLabelPipeline
from transformers import ElectraTokenizer
from model import ElectraForMultiLabelClassification
from pprint import pprint


tokenizer = ElectraTokenizer.from_pretrained("monologg/koelectra-base-finetuned-goemotions")
model = ElectraForMultiLabelClassification.from_pretrained("monologg/koelectra-base-finetuned-goemotions")

goemotions = MultiLabelPipeline(
    model=model,
    tokenizer=tokenizer,
    threshold=0.0,
)

texts = [
    "끊었던 담배 한 대 태우고 싶다. 이땅의 늙은 아버지들은 지금도 모르스 부호를 보내고 있다. 그것을 아는 자식들도 어찌할 방법이 없다.",
    "끊었던담배 한 대 태우고 싶다. 이땅의 늙은 아버지들은 지금도 모르스 부호를 보내고 있다. 그것을 아는 자식들도 어찌할 방법이 없다.",
    "말이 필요없는 영화 모두 꼭 한번쯤은 봐야할법한 영화입니다. 그리고 조여정이 개인적으로 크게 한껀 한것같습니다"
]

pprint(goemotions(texts))
```

**Comment by smbslt3** [comment]
threshold값을 바꾸니 잘 되네요
빠른 답변 감사합니다!
