### ISSUE TITLE
ModuleNotFoundError: No module named 'transformers.modeling_electra'

### ISSUE THREAD

**Issue by smbslt3** [monologg/GoEmotions-Korean#2]
transformers의 구조가 조금 바뀐 듯 합니다

`model.py`의 

`from transformers.modeling_electra import ElectraModel, ElectraPreTrainedModel`
부분을

`from transformers.models.electra.modeling_electra import ElectraModel, ElectraPreTrainedModel`
로 수정하니 정상 작동합니다

**Comment by monologg** [comment]
v4에서는 말씀해주신 부분으로 해야 정상작동합니다. 버전 디펜던시에 대해 매번 대응하기가 어려워 이 레포는 Readme에서 명시한 requirements 만 지원할 계획입니다!
